#基础设置
server:
  port: 8090
  servlet:
    context-path: /admin

#数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myAdmin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Jeff9302132
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html



#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/jeff/admin/*/*/*.xml
  global-config:
    db-config:
      db-type: mysql


#日志
logging:
  level:
    root: info
    org:
      springframework:
        web: debug